SCREEN_SIZE = (800, 600)
SCREEN_NAME = "my Game"
SCREEN_COLOR = (50, 50, 50)
FPS = 60
PLAYER_COUNT = 2

IMAGE_ROOT = 'images\\'

# רשת
ADDR_SERVER = ("127.0.0.1", 1234)

# הודעות
START_GAME = b"START"
GAME = b"GAME"
INFO = b"INFO"
WAIT = b"WAIT"
LOSE_GAME = b"LOSE"
WIN_GAME = b"WIN"

PLAYER_DATA = b"PLAYER_DATA"
ATTACK_POS = b"ATTACK_POS"
